version: '3'

services:
  chat2api:
    image: durianice/chat2api:latest
    container_name: chat2api
    restart: unless-stopped
    ports:
      - '5005:5005'
    volumes:
      - ./data:/app/data # 挂载一些需要保存的数据
    environment:
      - ARKOSE_TOKEN_URL=http://arkose:5006/token
      - PROXY_URL=$PROXY_URL
      # - CAPSOLVER_API_KEY=$CAPSOLVER_API_KEY
      # - POW_DIFFICULTY=$POW_DIFFICULTY
      # - RETRY_TIMES=$RETRY_TIMES
      # - HISTORY_DISABLED=$HISTORY_DISABLED
      # - CHATGPT_BASE_URL=$CHATGPT_BASE_URL
      # - API_PREFIX=$API_PREFIX

  arkose:
    image: lanqian528/funcaptcha_solver:latest
    container_name: funcaptcha_solver
    restart: unless-stopped
    ports:
      - '5006:5006'
    environment:
      - TZ=Asia/Shanghai # 设置时区